### PR TITLE
Codeserver docs + ubuntu 24 integration tests

### PR DESCRIPTION
**Pull request by joecorall**
Closes https://github.com/Islandora-Devops/isle-site-template/issues/46

### CODE REVIEW

**Comment by nigelgbanks** [comment]
This might fix the test failures. https://github.com/Islandora-Devops/isle-site-template/pull/74

**Review by nigelgbanks — APPROVED** [review]

**Comment by joecorall** [comment]
> This might fix the test failures. https://github.com/Islandora-Devops/isle-site-template/pull/74

I feel like the GitHub runner is having some resource issue effecting this. I am going to try creating a custom runner to see if that resolves this issue.

**Comment by nigelgbanks** [comment]
@joecorall I see that this is still in draft, do you want me to hold off on merging it?

**Comment by joecorall** [comment]
Great work on https://github.com/Islandora-Devops/isle-site-template/pull/76 @nigelgbanks. I put this in draft this morning knowing there was still something going on. With you fix I think we're good to merge!

**Pull request merged**
